### ISSUE TITLE
API for assembled panoramic views

### ISSUE THREAD

**Issue by vpicavet** [LI3DS/api-li3ds#1]
It would be useful to have an API for cubic panoramic, just like HERE does.

The JS API is here (!) : 
https://developer.here.com/javascript-apis/documentation/v3/maps/topics/panorama.html

API call : getClosestPanoramas with : lat and lng

Response : 

``` json
 {
"position":{"lat":48.87324644252658,"lng":2.358848350122571,"alt":95.758},
"url":"http://1.sli.data.here.com/226/0048/65/56/02/48655602",
"id":"48655602"
}
```

To get real images, there is a defined scheme for the URL : 

```
http://1.sli.data.here.com/226/0048/65/56/02/48655602_r11_f0_x7_y7.jpg?app_id=my_app_id&app_code=my_app_code

http://canonical_pano_url/<pano_id>_r<lod>_f<face>_x<img_tile_x>_y<img_tile_y>.jpg
```
- lod has values between 8 and 11 ( low definition to high definition)
- face goes from 0 to 5 ( North, East, South, West, Bottom, Top)
- images per load level (id starts at 0, top left to bottom right for each face) : 
  - 8 : 1
  - 9 : 2
  - 10 : 4
  - 11 : 8
- each jpg file is a 256x256 pixels image

Proposal : 
- a `/cubes/<id>` API entry point for cubes metadata with JSON response
- a `/cubes/tiles/<id>_r<lod>_f<face>_x<img_tile_x>_y<img_tile_y>.jpg` for jpg images

**Comment by vpicavet** [comment]
@ldgeo free to comment.
Note that we would still need an API for oriented images nontheless

**Comment by vpicavet** [comment]
Cubes are not the only option, changed the title to reflect this. Do we want to support different types of panoramic images or just one ?

Among the options : 
- equirectangular images
- cubic
- others ?

**Comment by mbredif** [comment]
For now, I propose to stick to the following (which is what I came across in the past)
- equirectangular, including crops (thetamin/thetamax, phimin/phimax)
- cubemaps, possibly incomplete (missing faces)
- unassembled panoramas (list of images from almost-colocated viewpints)

I do not think we should distinguish assembled and unassembled panoramas. For me it is just images with varying field of views (eg a fisheye image is almost a panorama by itself...). 
An interesting api would be to be able to select based on position and field of view : frustum-based selection !

**Comment by vpicavet** [comment]
One resource which could be interesting to get an idea of the existing mass market hardware providing 360° images and video : 
- https://developers.google.com/streetview/open-spherical-camera/
  implemented here for exemple : 
- https://developers.theta360.com/en/docs/v2.1/api_reference/
  The API is aimed at application development for hardware control, but gives an idea of data and metadata.
  It would be great to include video support beside static image support.

images and video examples : 
- https://theta360.com/fr/gallery/

**Comment by elemoine** [comment]
This is old stuff. Closing for now.
