### ISSUE TITLE
referencing objects by name

### ISSUE THREAD

**Issue by mbredif** [LI3DS/api-li3ds#11]
If [pg_li3ds#13](/LI3DS/pg_li3ds/pull/13) goes through, could objects be referenced by name rather than by id in all relevant entrypoints ?
This would enable, for instance, to do the sensor lookup by name in [micmac_li3ds#2](/LI3DS/micmac_li3ds/issues/2).

**Comment by elemoine** [comment]
Let's not change the model at this point in time :)
