### ISSUE TITLE
Move Dockerfile in a specific repo (docker-li3ds)

### ISSUE THREAD

**Issue by elemoine** [LI3DS/api-li3ds#29]
We also need web hooks to rebuild the Docker image on changes in api-li3ds, fdw-li3ds etc.

**Comment by mbredif** [comment]
+1

**Comment by ldgeo** [comment]
In progress in https://github.com/LI3DS/docker-li3ds

Even if we wanted to use debian jessie as a base image, there's no python-rosbag package for jessie.
So i decided to switch to ubuntu LTS version xenial (via the https://github.com/phusion/baseimage-docker image).

Moreover, as @arnaudbirk said yesterday there's a bug in the ros packages in debian stretch.
