### ISSUE TITLE
Cannot pass foreignpc table options through Swagger

### ISSUE THREAD

**Issue by elemoine** [LI3DS/api-li3ds#37]
The Swagger UI does not allow passing foreignpc table options when creating a foreignpc table. There are no fields displayed when expanding the "Options" fieldset.

![foreignpc-table-options](https://user-images.githubusercontent.com/76594/27787688-fa43c1fe-5fe5-11e7-9a15-abad0feb09c9.png)

**Comment by ldgeo** [comment]
JSON editor doesn't work with fields.Raw, i think we should avoid using the `SWAGGER_UI_JSONEDITOR: True` option, removed in 32e3274f3ded74d89e073fc9ad1c27556f7b5966
