### ISSUE TITLE
foreignpc issue with rosbag

### ISSUE THREAD

**Issue by elemoine** [LI3DS/api-li3ds#39]
The [code](https://github.com/LI3DS/api-li3ds/blob/master/api_li3ds/apis/foreignpc.py#L155-L157) that creates the "schema" table doesn't work with the Rosbag FDW. This is because a `topic` option is required when creating a "schema" table from a rosbag:

```sql
create foreign table rosbag_pointcloud2_format (
    schema text
) server rosbagserver
    options (
        topic '/Laser/velodyne_points'
        , metadata 'true'
);
```

Not sure what's the best way to fix that.

**Comment by ldgeo** [comment]
What do you means by "it doesn't work", what's the error ? I think `topic` is not required : https://github.com/LI3DS/fdw-li3ds/blob/master/fdwli3ds/rosbag_.py#L81 neither in https://github.com/LI3DS/fdw-rosbag/blob/pcpoint/rosbagfdw/__init__.py#L226

**Comment by mbredif** [comment]
My bad, `topic` was facultative at first, but it should now be mandatory. The lines @ldgeo mentionned should be updated.

**Comment by elemoine** [comment]
I am currently fixing this.

**Comment by elemoine** [comment]
And there are other issues. https://github.com/LI3DS/fdw-li3ds/pull/19 is one of them.
