### ISSUE TITLE
Table transfos

### ISSUE THREAD

**Issue by arnaudbirk** [LI3DS/api-li3ds#4]
Field parameters is not accessible on post query.

**Comment by mbredif** [comment]
more precisely, here : http://api.li3ds.io/#!/transfos/post_transfo

**Comment by ldgeo** [comment]
json inputs are not well managed by the swagger json editor, i changed config to avoid using it.
You can now copy/paste your payload directly in one field. (you can click on the example on right too)

**Comment by mbredif** [comment]
A little hacky but fits the bill :)
