### ISSUE TITLE
Default validity timestamps

### ISSUE THREAD

**Issue by mbredif** [LI3DS/api-li3ds#5]
By default a sensible validity time for `validity_end` attributes is +infinity and for `validity_start` attributes is somewhere in the distant past (0, -infinity...).
These default values could be added at the api-li3ds level or at the pg_li3ds level.

**Comment by mbredif** [comment]
similarly, calibration dates could default to now.

**Comment by ldgeo** [comment]
fixed here with 823776c

**Comment by mbredif** [comment]
Great, thanks !
