### ISSUE TITLE
Even fancier previews

### ISSUE THREAD

**Issue by mbredif** [LI3DS/api-li3ds#8]
Current preview does not show the sensors, the configuration name and the transform types.

**Comment by ldgeo** [comment]
Changed in `fancier preview` branch:
![preview](https://user-images.githubusercontent.com/1412193/27692417-ed450afa-5ce6-11e7-9566-2eda6528bf51.png)

**Comment by elemoine** [comment]
Was this branch merged into master already?

**Comment by ldgeo** [comment]
yes in https://github.com/LI3DS/api-li3ds/pull/9
